### PR TITLE
Enable editing of map properties

### LINKED ISSUE #129: Reminder: Never write into the LMT when clicking in the map tree or scrolling the scrollbar (Provide readonly mode?)
The RPG Maker editor has this bad behaviour to always write the LMT even when you don't do anything except for "clicking maps" and "scrolling around". This is SUPER BAD for game preservation because the file hash changes!

It means that only the LDB hash is reliable, for LMT it requires extracting the map tree and hashing this one.

Our editor shouldn't do this. It is unlikely that we will need hashing for "EasyRPG Games" but for game preservation of old games I consider such a feature crucial.

### PR DESCRIPTION
**Pull request by rueter37**
This PR enables editing all map properties except of the random dungeon generator settings. Moreover the RPG_RT.lmt no longer gets overwritten if a map is being opened (fixes #129).

### CODE REVIEW

**Review by fdelapena — APPROVED** [review]

**Comment by Ghabry** [comment]
Is it possible to replace most of this legacy code with LcfWidgetBinding stuff?

**Comment by rueter37** [comment]
Rebased this PR to resolve the dependencies. The rewrite to LcfWidgetBinding is still pending.

**Comment by rueter37** [comment]
Did the rewrite to LcfWidgetBinding now.

**Comment by rueter37** [comment]
The RPG_RT.lmt no longer gets overwritten if a map has been opened for game preservation purposes (see #129). The last remembered active map gets only changed now if the map has been changed.

**Pull request merged**
